// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxvkhsopgqocrfrnkqqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4dmtoc29wZ3FvY3Jmcm5rcXFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjA0OTksImV4cCI6MjA2Nzg5NjQ5OX0.4iA1NRRmKkQUumjxPckZ7-YSZ39IFyxcaHkkCScsLGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});